2018-12-23 15:32:15,152 - F:/web_OD/object_detcetion_test/server_test.py[line:220] - ERROR: HTTPConnectionPool(host='192.168.1.101', port=8080): Max retries exceeded with url: /photo1/getImgFileList/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000012FB88D0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
2018-12-23 15:37:41,400 - F:/web_OD/object_detcetion_test/server_test.py[line:220] - ERROR: HTTPConnectionPool(host='192.168.1.101', port=8080): Max retries exceeded with url: /photo1/getImgFileList/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000011FDE908>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
2018-12-23 15:38:23,058 - F:/web_OD/object_detcetion_test/server_test.py[line:220] - ERROR: HTTPConnectionPool(host='192.168.1.101', port=8080): Max retries exceeded with url: /photo1/getImgFileList/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000016615C88>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
2018-12-23 15:38:23,058 - F:/web_OD/object_detcetion_test/server_test.py[line:220] - ERROR: HTTPConnectionPool(host='192.168.1.101', port=8080): Max retries exceeded with url: /photo1/getImgFileList/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000016615C88>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
