2018-12-26 14:31:17,971 - F:/web_OD/object_detcetion_test/server_test.py[line:221] - ERROR: HTTPConnectionPool(host='10.104.2.89', port=8080): Max retries exceeded with url: /photo1/getImgFileList/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000001054DA58>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
2018-12-26 14:31:28,992 - F:/web_OD/object_detcetion_test/server_test.py[line:221] - ERROR: HTTPConnectionPool(host='10.104.2.89', port=8080): Max retries exceeded with url: /photo1/getImgFileList/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000001064B828>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
2018-12-26 14:31:28,992 - F:/web_OD/object_detcetion_test/server_test.py[line:221] - ERROR: HTTPConnectionPool(host='10.104.2.89', port=8080): Max retries exceeded with url: /photo1/getImgFileList/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000001064B828>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
2018-12-26 14:33:41,006 - F:/web_OD/object_detcetion_test/server_test.py[line:221] - ERROR: HTTPConnectionPool(host='10.104.2.89', port=8080): Max retries exceeded with url: /photo1/getImgFileList/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000011D95668>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
2018-12-26 14:33:52,032 - F:/web_OD/object_detcetion_test/server_test.py[line:221] - ERROR: HTTPConnectionPool(host='10.104.2.89', port=8080): Max retries exceeded with url: /photo1/getImgFileList/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000000120EC588>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
2018-12-26 14:33:52,032 - F:/web_OD/object_detcetion_test/server_test.py[line:221] - ERROR: HTTPConnectionPool(host='10.104.2.89', port=8080): Max retries exceeded with url: /photo1/getImgFileList/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000000120EC588>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
2018-12-26 14:34:03,058 - F:/web_OD/object_detcetion_test/server_test.py[line:221] - ERROR: HTTPConnectionPool(host='10.104.2.89', port=8080): Max retries exceeded with url: /photo1/getImgFileList/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000012132978>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
2018-12-26 14:34:03,058 - F:/web_OD/object_detcetion_test/server_test.py[line:221] - ERROR: HTTPConnectionPool(host='10.104.2.89', port=8080): Max retries exceeded with url: /photo1/getImgFileList/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000012132978>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
2018-12-26 14:34:03,058 - F:/web_OD/object_detcetion_test/server_test.py[line:221] - ERROR: HTTPConnectionPool(host='10.104.2.89', port=8080): Max retries exceeded with url: /photo1/getImgFileList/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000012132978>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
2018-12-26 14:35:15,864 - F:/web_OD/object_detcetion_test/server_test.py[line:221] - ERROR: HTTPConnectionPool(host='10.104.2.89', port=8080): Max retries exceeded with url: /photo1/getImgFileList/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000001053DA58>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
2018-12-26 14:35:27,667 - F:/web_OD/object_detcetion_test/server_test.py[line:221] - ERROR: HTTPConnectionPool(host='10.104.2.89', port=8080): Max retries exceeded with url: /photo1/getImgFileList/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000016AFC400>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
2018-12-26 14:35:27,667 - F:/web_OD/object_detcetion_test/server_test.py[line:221] - ERROR: HTTPConnectionPool(host='10.104.2.89', port=8080): Max retries exceeded with url: /photo1/getImgFileList/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000016AFC400>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
2018-12-26 14:35:38,981 - F:/web_OD/object_detcetion_test/server_test.py[line:221] - ERROR: HTTPConnectionPool(host='10.104.2.89', port=8080): Max retries exceeded with url: /photo1/getImgFileList/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000000150458D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
2018-12-26 14:35:38,981 - F:/web_OD/object_detcetion_test/server_test.py[line:221] - ERROR: HTTPConnectionPool(host='10.104.2.89', port=8080): Max retries exceeded with url: /photo1/getImgFileList/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000000150458D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
2018-12-26 14:35:38,981 - F:/web_OD/object_detcetion_test/server_test.py[line:221] - ERROR: HTTPConnectionPool(host='10.104.2.89', port=8080): Max retries exceeded with url: /photo1/getImgFileList/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000000150458D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
2018-12-26 14:39:03,433 - F:/web_OD/object_detcetion_test/server_test.py[line:221] - ERROR: HTTPConnectionPool(host='10.104.2.89', port=8080): Max retries exceeded with url: /photo1/getImgFileList/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000001053DA58>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
2018-12-26 14:39:14,487 - F:/web_OD/object_detcetion_test/server_test.py[line:221] - ERROR: HTTPConnectionPool(host='10.104.2.89', port=8080): Max retries exceeded with url: /photo1/getImgFileList/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000000108FEBA8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
2018-12-26 14:39:14,487 - F:/web_OD/object_detcetion_test/server_test.py[line:221] - ERROR: HTTPConnectionPool(host='10.104.2.89', port=8080): Max retries exceeded with url: /photo1/getImgFileList/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000000108FEBA8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
2018-12-26 14:39:25,494 - F:/web_OD/object_detcetion_test/server_test.py[line:221] - ERROR: HTTPConnectionPool(host='10.104.2.89', port=8080): Max retries exceeded with url: /photo1/getImgFileList/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000000109B3BA8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
2018-12-26 14:39:25,494 - F:/web_OD/object_detcetion_test/server_test.py[line:221] - ERROR: HTTPConnectionPool(host='10.104.2.89', port=8080): Max retries exceeded with url: /photo1/getImgFileList/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000000109B3BA8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
2018-12-26 14:39:25,494 - F:/web_OD/object_detcetion_test/server_test.py[line:221] - ERROR: HTTPConnectionPool(host='10.104.2.89', port=8080): Max retries exceeded with url: /photo1/getImgFileList/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000000109B3BA8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
2018-12-26 14:45:30,696 - F:/web_OD/object_detcetion_test/server_test.py[line:221] - ERROR: ('Connection aborted.', ConnectionAbortedError(10053, '您的主机中的软件中止了一个已建立的连接。', None, 10053, None))
2018-12-26 14:45:50,731 - F:/web_OD/object_detcetion_test/server_test.py[line:221] - ERROR: ('Connection aborted.', ConnectionAbortedError(10053, '您的主机中的软件中止了一个已建立的连接。', None, 10053, None))
2018-12-26 14:45:50,731 - F:/web_OD/object_detcetion_test/server_test.py[line:221] - ERROR: ('Connection aborted.', ConnectionAbortedError(10053, '您的主机中的软件中止了一个已建立的连接。', None, 10053, None))
2018-12-26 16:01:39,506 - F:/web_OD/object_detcetion_test/server_test.py[line:221] - ERROR: ('Connection aborted.', ConnectionAbortedError(10053, '您的主机中的软件中止了一个已建立的连接。', None, 10053, None))
2018-12-26 16:03:24,880 - F:/web_OD/object_detcetion_test/server_test.py[line:221] - ERROR: ('Connection aborted.', ConnectionAbortedError(10053, '您的主机中的软件中止了一个已建立的连接。', None, 10053, None))
2018-12-26 16:06:05,526 - F:/web_OD/object_detcetion_test/server_test.py[line:221] - ERROR: ('Connection aborted.', ConnectionAbortedError(10053, '您的主机中的软件中止了一个已建立的连接。', None, 10053, None))
2018-12-26 16:06:05,526 - F:/web_OD/object_detcetion_test/server_test.py[line:221] - ERROR: ('Connection aborted.', ConnectionAbortedError(10053, '您的主机中的软件中止了一个已建立的连接。', None, 10053, None))
2018-12-26 16:06:15,553 - F:/web_OD/object_detcetion_test/server_test.py[line:221] - ERROR: ('Connection aborted.', ConnectionAbortedError(10053, '您的主机中的软件中止了一个已建立的连接。', None, 10053, None))
2018-12-26 16:06:15,553 - F:/web_OD/object_detcetion_test/server_test.py[line:221] - ERROR: ('Connection aborted.', ConnectionAbortedError(10053, '您的主机中的软件中止了一个已建立的连接。', None, 10053, None))
2018-12-26 16:06:15,553 - F:/web_OD/object_detcetion_test/server_test.py[line:221] - ERROR: ('Connection aborted.', ConnectionAbortedError(10053, '您的主机中的软件中止了一个已建立的连接。', None, 10053, None))
